pipeline {
    agent {
        kubernetes {
        label 'mypod'
        yaml """
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: mvn
    image: maven:3.3.9-jdk-8-alpine
    command:
    - cat
    tty: true
"""
        }
    }
    stages {
        stage('Checkout') { 
            steps {
                git credentialsId: "${github_creds}" , url: "${github_repo}" 
            }
        }
        stage('Build') { 
            steps {
                container ('mvn') {
                    sh 'mvn -B -DskipTests clean package' 
                }
            }
        }
    }
}
